<?php
// module/Album/view/product/product/add.phtml:
$title = 'Add new product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('product', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);?>
<!--//echo $this->formCollection($form);-->
<?php echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('product_name'));?><br />
<?php echo $this->formRow($form->get('description'));?><br />
<?php echo $this->formRow($form->get('price'));?><br />
<?php echo $this->formRow($form->get('image'));?><br />
<?php echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();?>


