<?php
// module/Album/view/product/product/add.phtml:
$title = 'Add new product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('product', array('action' => 'add')));
//$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
//echo $this->formRow($form->get('image'));
//echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


