<?php
// module/Product/view/product/product/edit.phtml:
$title = 'Edit product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'product',
    array(
        'action' => 'add',
        'id'     => $this->id,
    )
));
$form->prepare();
echo $this->form()->openTag($form);?>
<?php echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('product_name'));?> <br />
<?php echo $this->formRow($form->get('description'));?> <br />
<?php echo $this->formRow($form->get('price'));?> <br />
<?php echo $this->formRow($form->get('image'));?> <br />
<?php echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();?>