
<?php 
if($this->zfcUserIdentity()) { ?>
    <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
    <div style="clear:both;"></div>
<?php } else { ?>
<p>
    <a href="http://newzend/user/login">Sign In</a> | <a href="http://newzend/user/register">Sign Up</a>
</p>
<?php } ?>
<?php
// module/Product/view/product/product/index.phtml:
$title = 'My products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if ($this->zfcUserIdentity()) { ?>  
	<p>
	    <a href="<?php echo $this->url('product', array('action'=>'add'));?>">Add new product</a>
	</p>
<?php } ?>
<?php if ($products->count() != 0) { ?>
<table class="table">
<tr>
    <th>Название товара</th>
    <th>Описание</th>
    <th>Цена</th>
    <th>Изображение</th>
    <th>&nbsp;</th>
</tr>

<?php //var_dump($this->escapeHtml($products->product_name)); ?>
<?php foreach ($products as $product) : ?>
<tr>
    <td><?php echo $this->escapeHtml($product->product_name);?></td>

    <td><?php echo $this->escapeHtml($product->description);?></td>
    <td><?php echo $this->escapeHtml($product->price);?></td>
    <td><?php echo "<img src='/img/" . $this->escapeHtml($product->image) . "'/>";?></td>
    <td>
        <?php if ($this->zfcUserIdentity()) { ?> 
            <a href="<?php echo $this->url('product',
                array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
            <a href="<?php echo $this->url('product',
                array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
        <?php } ?>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php } else { ?>
    <h1>Записей нет.</h1>   
<?php }  ?>

